// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/09/2025 15:52:53
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/Moi/MOI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Moi/MOI/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Moi/MOI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Moi/MOI/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Moi/MOI/plugins/**/*.{js,ts,mjs}","E:/Moi/MOI/composables/**/*.{js,ts,mjs}","E:/Moi/MOI/utils/**/*.{js,ts,mjs}","E:/Moi/MOI/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Moi/MOI/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/Moi/MOI/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/Moi/MOI/app.config.{js,ts,mjs}"]}},
{"darkMode":"class","theme":{"extend":{"colors":{"primary":{"50":"#eff6ff","100":"#dbeafe","200":"#bfdbfe","300":"#93c5fd","400":"#60a5fa","500":"#3b82f6","600":"#2563eb","700":"#1d4ed8","800":"#1e40af","900":"#1e3a8a","950":"#172554"},"secondary":{"50":"#faf5ff","100":"#f3e8ff","200":"#e9d5ff","300":"#d8b4fe","400":"#c084fc","500":"#a855f7","600":"#9333ea","700":"#7c3aed","800":"#6b21a8","900":"#581c87","950":"#3b0764"}},"fontFamily":{"sans":["Inter","sans-serif"],"display":["Poppins","sans-serif"]},"animation":{"fade-in":"fadeIn 0.5s ease-in-out","slide-up":"slideUp 0.5s ease-out","slide-down":"slideDown 0.5s ease-out","scale-in":"scaleIn 0.3s ease-out","glow":"glow 2s ease-in-out infinite alternate","float":"float 6s ease-in-out infinite","pulse-slow":"pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite"},"keyframes":{"fadeIn":{"0%":{"opacity":"0"},"100%":{"opacity":"1"}},"slideUp":{"0%":{"transform":"translateY(20px)","opacity":"0"},"100%":{"transform":"translateY(0)","opacity":"1"}},"slideDown":{"0%":{"transform":"translateY(-20px)","opacity":"0"},"100%":{"transform":"translateY(0)","opacity":"1"}},"scaleIn":{"0%":{"transform":"scale(0.9)","opacity":"0"},"100%":{"transform":"scale(1)","opacity":"1"}},"glow":{"0%":{"boxShadow":"0 0 20px rgba(59, 130, 246, 0.5)"},"100%":{"boxShadow":"0 0 30px rgba(59, 130, 246, 0.8)"}},"float":{"0%, 100%":{"transform":"translateY(0px)"},"50%":{"transform":"translateY(-20px)"}}}}}},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["17"] = "E:/Moi/MOI/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;